- name: Install `pip`
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: install docker
  include_tasks: install_docker.yml
  
- name: install docker-compose
  include_tasks: install_compose.yml